### ISSUE TITLE
TypeError: stream.on is not a function

### ISSUE THREAD

**Issue by zuck** [fastify/fastify-cli#235]
## 🐛 Bug Report

Using the option `-P` for pretty-printing logs seems to generate issues with `pump` since yesterday.

If I remove the option, the app is launched as expected:

```bash
> knex migrate:latest --env development && fastify start -P -o -l info app.js

Using environment: development
Already up to date
/Users/ebertoldi/Projects/jarwin/api/node_modules/pump/index.js:26
  stream.on('close', function () {
         ^

TypeError: stream.on is not a function
    at destroyer (/Users/ebertoldi/Projects/jarwin/api/node_modules/pump/index.js:26:10)
    at /Users/ebertoldi/Projects/jarwin/api/node_modules/pump/index.js:70:12
    at Array.map (<anonymous>)
    at pump (/Users/ebertoldi/Projects/jarwin/api/node_modules/pump/index.js:67:26)
    at runFastify (/Users/ebertoldi/Projects/jarwin/api/node_modules/fastify-cli/start.js:101:5)
    at start (/Users/ebertoldi/Projects/jarwin/api/node_modules/fastify-cli/start.js:50:10)
    at Command.cli [as func] (/Users/ebertoldi/Projects/jarwin/api/node_modules/fastify-cli/start.js:139:3)
    at Command.call (/Users/ebertoldi/Projects/jarwin/api/node_modules/commist/index.js:105:8)
    at Object.parse (/Users/ebertoldi/Projects/jarwin/api/node_modules/commist/index.js:54:19)
    at Object.<anonymous> (/Users/ebertoldi/Projects/jarwin/api/node_modules/fastify-cli/cli.js:25:21)
```

## To Reproduce

1. Create a new fastify app with the CLI.
2. Launch the app passing the `-P` option to the `fastify start` command.

## Expected behavior

The CLI should start the application as before printing pretty logs.

## Your Environment

- *node version*: 10, 12
- *fastify version*: > 2.12.1
- *fastify-cli version*: >1.4.0
- *os*: Mac, Linux

**Comment by Eomm** [comment]
Thanks for reporting, I reproduced it wth:

```
npx fastify-cli generate pretty
cd pretty/
npm i
// edit the package.json
```

To solve:
```
npm ls pino-colada
// you should see 1.6.0

// to fix run:
npm i pino-colada@1.5.1
```
