### ISSUE TITLE
plugin must be a function or a promise error

### ISSUE THREAD

**Issue by Adityapanther** [fastify/fastify-cli#323]
## 🐛 Bug Report

After installing `fastify-cli` and running with command `npm start` getting error which is written below. if i am running server with normal command `node server.js` my server running well

## Getting error

```js
fastify_demo@1.0.0 start C:\Users\Aditya_kumar\Desktop\demo_classes\fastify
> fastify start server.js

Error: plugin must be a function or a promise
    at assertPlugin (C:\Users\Aditya_kumar\Desktop\demo_classes\fastify\node_modules\avvio\boot.js:200:11)
    at Boot._addPlugin (C:\Users\Aditya_kumar\Desktop\demo_classes\fastify\node_modules\avvio\boot.js:233:12)
    at Boot.use (C:\Users\Aditya_kumar\Desktop\demo_classes\fastify\node_modules\avvio\boot.js:209:25)
    at Object.server.<computed> [as register] (C:\Users\Aditya_kumar\Desktop\demo_classes\fastify\node_modules\avvio\boot.js:33:14)
    at runFastify (C:\Users\Aditya_kumar\Desktop\demo_classes\fastify\node_modules\fastify-cli\start.js:128:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fastify_demo@1.0.0 start: `fastify start server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fastify_demo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Aditya_kumar\AppData\Roaming\npm-cache\_logs\2021-03-04T04_52_44_630Z-debug.log
```

## Expected behavior

```js
// server is running
```

## Your Environment

- *node version*: 14, 16, 0
- *fastify version*: >=3.13.0
-  *fastify version*: >=2.8.0
- *os*: Windows

**Comment by mcollina** [comment]
What is the content of `server.js`?

**Comment by Adityapanther** [comment]
## content of `server.js` file

```
const fastify = require('fastify');
const app = fastify({logger: true});

// register routes
const rou = require("./routes/firstRoutes");

app.register(rou);

const start = async function(){
    try{
       await app.listen("3000")
    }catch(e){
        app.log.error(e);
    }
}

start();

```

## and content of `routes/firstRoutes.js`

```
async function hell(app, options) {
    
    app.get('/', async (req, res) => {
        return {"greeting":"hello"};
    });

    app.get("/user", async (req, rep) =>{
        return {"user":"he all she"};
    });
};

module.exports = hell;
```

**Comment by mcollina** [comment]
If you read the docs, https://github.com/fastify/fastify-cli#start shows that you need to point it to a plugin to start, not a server. You can start the server just by using `node server`.

**Comment by Adityapanther** [comment]
so,` fastify start filename.js` for only plugins start

**Comment by mcollina** [comment]
yes!
