### ISSUE TITLE
fastify docs doesn't work

### ISSUE THREAD

**Issue by ManUtopiK** [fastify/fastify-cli#341]
## 🐛 Bug Report

When I run `fastify docs`, it return this error:
```bash
internal/fs/utils.js:299
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:582:3)
    at tryReadSync (fs.js:358:20)
    at Object.readFileSync (fs.js:395:19)
    at Command.renderDocs [as func] (/Users/manu/.nvm/versions/node/v14.13.0/lib/node_modules/fastify-cli/docs.js:18:27)
    at Command.call (/Users/manu/.nvm/versions/node/v14.13.0/lib/node_modules/fastify-cli/node_modules/commist/index.js:105:8)
    at Object.parse (/Users/manu/.nvm/versions/node/v14.13.0/lib/node_modules/fastify-cli/node_modules/commist/index.js:54:19)
    at Object.<anonymous> (/Users/manu/.nvm/versions/node/v14.13.0/lib/node_modules/fastify-cli/cli.js:33:21)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
```

## Your Environment

- *node version*: v14.13.0
- *fastify version*: ^3.12.0
- *os*: Mac osx 10.15.6
- I use esm module with `"type": "module"` in the package.json
- I also use "link-module-alias": "^1.2.0"

**Comment by mcollina** [comment]
https://github.com/fastify/fastify-cli/blob/8049f1298761549a833add7cdf30154df00efc58/docs.js#L18 is missing a check to see if the file is actually a normal file and not a directory... in which case we should recourse.

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by ManUtopiK** [comment]
✅   Challenge accepted!
