### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by benjaminviaud** [fastify/fastify-cli#351]
## 🐛 Bug Report

I created a simple fastify server but when I start with fastify-cli the console says :

TypeError: Cannot read property 'length' of undefined
    at isInvalidAsyncPlugin (/Users/ben/Sites/itsmediasarl/application/backend/node_modules/fastify-cli/util.js:42:17)
    at requireServerPluginFromPath (/Users/ben/Sites/itsmediasarl/application/backend/node_modules/fastify-cli/util.js:81:7)
    at async runFastify (/Users/ben/Sites/itsmediasarl/application/backend/node_modules/fastify-cli/start.js:89:12)

## To Reproduce

Index.js
```js
'use strict'

import pino from 'pino'
import chalk from 'chalk'
import * as dotenv from 'dotenv'
import Fastify from 'fastify'

const logger = pino({ level: 'error' }, './logs/error.log')
dotenv.config()

// Instance de fastify
const app = Fastify({ logger })

// Routes
app.get('/hello', (request, reply) => {
  return { hello: 'world' }
})

// Démarrage du serveur
async function start() {
  try {
    await app.listen(3001, 'localhost')

    console.log(chalk.green('Serveur démarré avec succès !'))
  } catch (err) {
    console.log(chalk.red('Erreur lors du démarrage du serveur : ', err))
    process.exit(1)
  }
}
start()

```
Package.json
```js
"start": "fastify start index.js"
```

## Your Environment

- *node version*: v14.16.1
- *fastify version*: 3.15.0
- *fastify-cli version*: 2.10.0
- *os*: Mac

**Comment by benjaminviaud** [comment]
Sorry, I am using fastify-cli incorrectly.
