### ISSUE TITLE
Fastify cli marked terminal bug

### ISSUE THREAD

**Issue by olischmidt123** [fastify/fastify-cli#460]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.0.0

### Plugin version

^3.0.0

### Node.js version

v10.19.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-1028-aws x86_64)

### Description

Fastify cli version: 2.15.0

When trying to start up my fastify webserver I get the following error. This comes up whenever I use any fastify cli command.

Command: fastify start --address 0.0.0.0 -l warn app.js

Error:

/usr/local/lib/node_modules/fastify-cli/node_modules/marked-terminal/index.cjs:333
			&& Number(osRelease[2]) >= 10_586
			                           ^^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/fastify-cli/node_modules/blessed-contrib/lib/widget/markdown.js:5:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

### Steps to Reproduce

1. install Fastify cli version: 2.15.0
2. create fastify project
3. run:  fastify start --address 0.0.0.0 -l warn app.js

### Expected Behavior

Webserver started

**Comment by mcollina** [comment]
Confirmed, we have failing test on Node v10. I guess marked-terminal shipped some unexpected breaking change. Would you like to send a PR to fix this? We should disable the docs feature in Node v10.

I would also note that Node v10 is long deprecated and should not be used.

**Comment by darkgl0w** [comment]
related: https://github.com/fastify/fastify-cli/issues/467

`marked-terminal` now makes use of the `node:<core_module>` syntax.
This has been supported only since Node.js 16 and its been back ported to Node.js 14.18.0 and greater only.
