### ISSUE TITLE
PM2

### ISSUE THREAD

**Issue by lgertel** [fastify/fastify-cli#83]
It's possible to use PM2 with fastify-cli?

**Comment by mcollina** [comment]
I think so, you might want to try `pm2 start ./node_modules/.bin/fastify start app.js`

Let me know how it goes!

**Comment by jafri** [comment]
I get the error

```
[PM2][ERROR] script not found : /home/jafri/fast-bloks/start
script not found : /home/jafri/fast-bloks/start
```

**Comment by mcollina** [comment]
@lgertel would you mind adding some instructions in the README on how to use fastify-cli with pm2?

**Comment by jafri** [comment]
@igertel still not sure how to run with pm2

**Comment by mcollina** [comment]
@jafri `pm2 start 'fastify start app.js'` works for me.

**Comment by ngprnk** [comment]
I get this error while running `fastify` with `pm2`

```
SyntaxError: Invalid or unexpected token
1|worker   |     at wrapSafe (internal/modules/cjs/loader.js:979:16)
1|worker   |     at Module._compile (internal/modules/cjs/loader.js:1027:27)
1|worker   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
1|worker   |     at Module.load (internal/modules/cjs/loader.js:928:32)
1|worker   |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

**Comment by kibertoad** [comment]
Are you trying to run TypeScript? Are you using older Node version?

**Comment by ngprnk** [comment]
> Are you trying to run TypeScript? Are you using older Node version?
node version
```v14.16.1```
i have `  "type": "module"` in my package.json
