### ISSUE TITLE
Call decorator inside listen.

### ISSUE THREAD

**Issue by lgertel** [fastify/fastify-cli#90]
Hello everyone.
I think that without cli is possible to call a decorator inside the .listener method to start the server.

Is this possible with cli?
Ty!

**Comment by delvedor** [comment]
Hi! The cli calls the `listen` method internally.
If you need to do something custom inside `listen` you should not use the cli.
Otherwise, you can try with the [`ready`](https://www.fastify.io/docs/latest/Server-Methods/#ready) method.

**Comment by lgertel** [comment]
@delvedor great!
It's possible to call a decorator inside it then? Something like this:
```
fastify.ready().then(() => {
    fastify.setAclRules({
      routes: routes
    })
  }, (err) => {
    console.log(err)
  })
```

**Comment by delvedor** [comment]
Yes!

**Comment by lgertel** [comment]
@delvedor 
```
(node:41226) UnhandledPromiseRejectionWarning: TypeError: fastify.retrieveRoutes is not a function
    at fastify.ready.then (/Users/lgertel/nomikos/plugins/acl.js:42:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:41226) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:41226) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Not sure what I'm doing wrong
```
fastify.ready().then(() => {
    fastify.retrieveRoutes()
  }, (err) => {
    console.log(err)
  })
```

**Comment by delvedor** [comment]
If you have registered `retrieveRoutes` inside another plugin you should use the fastify instance given by `ready` in the callback:
```js
fastify.ready(function (err, instance, done) {
  if (err) throw err
  instance.retrieveRoutes()
  done()
})
```
